package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.container.Container;

import java.util.Date;

public class ContainerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_host
     *
     * @mbg.generated
     */
    private String containerHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_user
     *
     * @mbg.generated
     */
    private String containerUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_pwd
     *
     * @mbg.generated
     */
    private String containerPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_port
     *
     * @mbg.generated
     */
    private Integer containerPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_name
     *
     * @mbg.generated
     */
    private String containerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container.container_desc
     *
     * @mbg.generated
     */
    private String containerDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_container
     *
     * @mbg.generated
     */
    public ContainerEntity(Integer id, Integer developerId, String containerHost, String containerUser, String containerPwd, Integer containerPort, Date lastModifyTime, Date createTime, String containerName, String containerDesc) {
        this.id = id;
        this.developerId = developerId;
        this.containerHost = containerHost;
        this.containerUser = containerUser;
        this.containerPwd = containerPwd;
        this.containerPort = containerPort;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
        this.containerName = containerName;
        this.containerDesc = containerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.id
     *
     * @return the value of devops_container.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.developer_id
     *
     * @return the value of devops_container.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_host
     *
     * @return the value of devops_container.container_host
     *
     * @mbg.generated
     */
    public String getContainerHost() {
        return containerHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_user
     *
     * @return the value of devops_container.container_user
     *
     * @mbg.generated
     */
    public String getContainerUser() {
        return containerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_pwd
     *
     * @return the value of devops_container.container_pwd
     *
     * @mbg.generated
     */
    public String getContainerPwd() {
        return containerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_port
     *
     * @return the value of devops_container.container_port
     *
     * @mbg.generated
     */
    public Integer getContainerPort() {
        return containerPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.last_modify_time
     *
     * @return the value of devops_container.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.create_time
     *
     * @return the value of devops_container.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_name
     *
     * @return the value of devops_container.container_name
     *
     * @mbg.generated
     */
    public String getContainerName() {
        return containerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container.container_desc
     *
     * @return the value of devops_container.container_desc
     *
     * @mbg.generated
     */
    public String getContainerDesc() {
        return containerDesc;
    }

    public Container toContainer() {
        Container container = new Container();
        container.setAddress(this.containerHost);
        container.setDesc(this.containerDesc);
        container.setName(this.containerName);
        return container;
    }
}