package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.devops.DeployPackage;

import java.util.Date;

public class DeployEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.deploy_container
     *
     * @mbg.generated
     */
    private Integer deployContainer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.java_build
     *
     * @mbg.generated
     */
    private Integer javaBuild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.deploy_path
     *
     * @mbg.generated
     */
    private String deployPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.deploy_with_script
     *
     * @mbg.generated
     */
    private Integer deployWithScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_deploy.env
     *
     * @mbg.generated
     */
    private String env;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_deploy
     *
     * @mbg.generated
     */
    public DeployEntity(Integer id, Integer developerId, Integer deployContainer, Integer javaBuild, String deployPath, Integer deployWithScript, Date lastModifyTime, Date createTime, String version, String env) {
        this.id = id;
        this.developerId = developerId;
        this.deployContainer = deployContainer;
        this.javaBuild = javaBuild;
        this.deployPath = deployPath;
        this.deployWithScript = deployWithScript;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
        this.version = version;
        this.env = env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.id
     *
     * @return the value of devops_java_deploy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.developer_id
     *
     * @return the value of devops_java_deploy.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.deploy_container
     *
     * @return the value of devops_java_deploy.deploy_container
     *
     * @mbg.generated
     */
    public Integer getDeployContainer() {
        return deployContainer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.java_build
     *
     * @return the value of devops_java_deploy.java_build
     *
     * @mbg.generated
     */
    public Integer getJavaBuild() {
        return javaBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.deploy_path
     *
     * @return the value of devops_java_deploy.deploy_path
     *
     * @mbg.generated
     */
    public String getDeployPath() {
        return deployPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.deploy_with_script
     *
     * @return the value of devops_java_deploy.deploy_with_script
     *
     * @mbg.generated
     */
    public Integer getDeployWithScript() {
        return deployWithScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.last_modify_time
     *
     * @return the value of devops_java_deploy.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.create_time
     *
     * @return the value of devops_java_deploy.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.version
     *
     * @return the value of devops_java_deploy.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_deploy.env
     *
     * @return the value of devops_java_deploy.env
     *
     * @mbg.generated
     */
    public String getEnv() {
        return env;
    }

    public DeployPackage toDeployPackage(ContainerEntity containerEntity, DeployEntity deployEntity) {
        DeployPackage deployPackage = new DeployPackage();
        deployPackage.setContainerName(containerEntity.getContainerName());
        deployPackage.setRemoteDeployPath(deployEntity.getDeployPath());
        return deployPackage;
    }
}