package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.developer.Developer;

import java.util.Date;

public class DeveloperEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.developer_username
     *
     * @mbg.generated
     */
    private String developerUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.developer_password
     *
     * @mbg.generated
     */
    private String developerPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.developer_email
     *
     * @mbg.generated
     */
    private String developerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.developer_phone
     *
     * @mbg.generated
     */
    private String developerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.developer_token
     *
     * @mbg.generated
     */
    private String developerToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_developer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_developer
     *
     * @mbg.generated
     */
    public DeveloperEntity(Integer id, String developerUsername, String developerPassword, String developerEmail, String developerPhone, String developerToken, Date lastModifyTime, Date createTime) {
        this.id = id;
        this.developerUsername = developerUsername;
        this.developerPassword = developerPassword;
        this.developerEmail = developerEmail;
        this.developerPhone = developerPhone;
        this.developerToken = developerToken;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.id
     *
     * @return the value of devops_developer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.developer_username
     *
     * @return the value of devops_developer.developer_username
     *
     * @mbg.generated
     */
    public String getDeveloperUsername() {
        return developerUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.developer_password
     *
     * @return the value of devops_developer.developer_password
     *
     * @mbg.generated
     */
    public String getDeveloperPassword() {
        return developerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.developer_email
     *
     * @return the value of devops_developer.developer_email
     *
     * @mbg.generated
     */
    public String getDeveloperEmail() {
        return developerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.developer_phone
     *
     * @return the value of devops_developer.developer_phone
     *
     * @mbg.generated
     */
    public String getDeveloperPhone() {
        return developerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.developer_token
     *
     * @return the value of devops_developer.developer_token
     *
     * @mbg.generated
     */
    public String getDeveloperToken() {
        return developerToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.last_modify_time
     *
     * @return the value of devops_developer.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_developer.create_time
     *
     * @return the value of devops_developer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setDeveloperUsername(String developerUsername) {
        this.developerUsername = developerUsername;
    }

    public void setDeveloperPassword(String developerPassword) {
        this.developerPassword = developerPassword;
    }

    public void setDeveloperEmail(String developerEmail) {
        this.developerEmail = developerEmail;
    }

    public void setDeveloperPhone(String developerPhone) {
        this.developerPhone = developerPhone;
    }

    public void setDeveloperToken(String developerToken) {
        this.developerToken = developerToken;
    }

    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Developer toDeveloper() {
        Developer developer = new Developer(
                this.id,
                this.developerUsername,
                this.developerEmail,
                this.developerPhone,
                this.developerToken,
                this.lastModifyTime,
                this.createTime
        );
        return developer;
    }

    @Override
    public String toString() {
        return "DeveloperEntity{" +
                "id=" + id +
                ", developerUsername='" + developerUsername + '\'' +
                ", developerPassword='" + developerPassword + '\'' +
                ", developerEmail='" + developerEmail + '\'' +
                ", developerPhone='" + developerPhone + '\'' +
                ", developerToken='" + developerToken + '\'' +
                ", lastModifyTime=" + lastModifyTime +
                ", createTime=" + createTime +
                '}';
    }
}