package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.devlog.DevopsLogEntity;

import java.util.Date;

public class DevopsOpLogEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.command
     *
     * @mbg.generated
     */
    private String command;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.args
     *
     * @mbg.generated
     */
    private String args;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.dtime
     *
     * @mbg.generated
     */
    private String dtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.ddesc
     *
     * @mbg.generated
     */
    private String ddesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    public DevopsOpLogEntity(Integer id, Integer developerId, String username, String command, String args, String dtime, String content, String ddesc, String result, Date lastModifyTime, Date createTime) {
        this.id = id;
        this.developerId = developerId;
        this.username = username;
        this.command = command;
        this.args = args;
        this.dtime = dtime;
        this.content = content;
        this.ddesc = ddesc;
        this.result = result;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
    }

    public DevopsOpLogEntity(DevopsLogEntity devopsLogEntity) {
        this.developerId =1;
        this.command = devopsLogEntity.command;
        this.ddesc  = devopsLogEntity.desc;
        this.username = devopsLogEntity.user;
        this.content = devopsLogEntity.content;
        this.args = devopsLogEntity.args;
        this.result = devopsLogEntity.result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.id
     *
     * @return the value of devops_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.developer_id
     *
     * @return the value of devops_log.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.username
     *
     * @return the value of devops_log.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.command
     *
     * @return the value of devops_log.command
     *
     * @mbg.generated
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.args
     *
     * @return the value of devops_log.args
     *
     * @mbg.generated
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.dtime
     *
     * @return the value of devops_log.dtime
     *
     * @mbg.generated
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.content
     *
     * @return the value of devops_log.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.ddesc
     *
     * @return the value of devops_log.ddesc
     *
     * @mbg.generated
     */
    public String getDdesc() {
        return ddesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.result
     *
     * @return the value of devops_log.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.last_modify_time
     *
     * @return the value of devops_log.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_log.create_time
     *
     * @return the value of devops_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    public void setDeveloperId(Integer developerId) {
        this.developerId = developerId;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    public void setArgs(String args) {
        this.args = args;
    }

    public void setDtime(String dtime) {
        this.dtime = dtime;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setDdesc(String ddesc) {
        this.ddesc = ddesc;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}