package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.devops.GitProject;

import java.util.Date;

public class GitProjectEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.git_path
     *
     * @mbg.generated
     */
    private String gitPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.git_user
     *
     * @mbg.generated
     */
    private Integer gitUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_project.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_git_project
     *
     * @mbg.generated
     */
    public GitProjectEntity(Integer id, Integer developerId, String projectName, String gitPath, Integer gitUser, Date lastModifyTime, Date createTime) {
        this.id = id;
        this.developerId = developerId;
        this.projectName = projectName;
        this.gitPath = gitPath;
        this.gitUser = gitUser;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.id
     *
     * @return the value of devops_git_project.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.developer_id
     *
     * @return the value of devops_git_project.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.project_name
     *
     * @return the value of devops_git_project.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.git_path
     *
     * @return the value of devops_git_project.git_path
     *
     * @mbg.generated
     */
    public String getGitPath() {
        return gitPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.git_user
     *
     * @return the value of devops_git_project.git_user
     *
     * @mbg.generated
     */
    public Integer getGitUser() {
        return gitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.last_modify_time
     *
     * @return the value of devops_git_project.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_project.create_time
     *
     * @return the value of devops_git_project.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public GitProject toGitProject() {
        GitProject gitProject = new GitProject();
        gitProject.setGitCodePath(this.gitPath);
        return gitProject;
    }
}