package com.cenostack.ms.devops.entity;

import java.util.Date;

public class GitUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.git_user_name
     *
     * @mbg.generated
     */
    private String gitUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.git_user_pwd
     *
     * @mbg.generated
     */
    private String gitUserPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_git_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_git_user
     *
     * @mbg.generated
     */
    public GitUserEntity(Integer id, Integer developerId, String gitUserName, String gitUserPwd, Date lastModifyTime, Date createTime) {
        this.id = id;
        this.developerId = developerId;
        this.gitUserName = gitUserName;
        this.gitUserPwd = gitUserPwd;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.id
     *
     * @return the value of devops_git_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.developer_id
     *
     * @return the value of devops_git_user.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.git_user_name
     *
     * @return the value of devops_git_user.git_user_name
     *
     * @mbg.generated
     */
    public String getGitUserName() {
        return gitUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.git_user_pwd
     *
     * @return the value of devops_git_user.git_user_pwd
     *
     * @mbg.generated
     */
    public String getGitUserPwd() {
        return gitUserPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.last_modify_time
     *
     * @return the value of devops_git_user.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_git_user.create_time
     *
     * @return the value of devops_git_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }
}