package com.cenostack.ms.devops.entity;

import com.cenostack.ms.devops.dto.devops.BuildCode;

import java.util.Date;

public class JavaBuildEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.developer_id
     *
     * @mbg.generated
     */
    private Integer developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.git_project_id
     *
     * @mbg.generated
     */
    private Integer gitProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.git_branch
     *
     * @mbg.generated
     */
    private String gitBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.code_path
     *
     * @mbg.generated
     */
    private String codePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.build_path
     *
     * @mbg.generated
     */
    private String buildPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.build_type
     *
     * @mbg.generated
     */
    private String buildType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.jvm_options
     *
     * @mbg.generated
     */
    private String jvmOptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_java_build.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    public JavaBuildEntity(Integer id, Integer developerId, String projectName, Integer gitProjectId, String gitBranch, String codePath, String buildPath, String version, String buildType, String jvmOptions, Date lastModifyTime, Date createTime) {
        this.id = id;
        this.developerId = developerId;
        this.projectName = projectName;
        this.gitProjectId = gitProjectId;
        this.gitBranch = gitBranch;
        this.codePath = codePath;
        this.buildPath = buildPath;
        this.version = version;
        this.buildType = buildType;
        this.jvmOptions = jvmOptions;
        this.lastModifyTime = lastModifyTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.id
     *
     * @return the value of devops_java_build.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.developer_id
     *
     * @return the value of devops_java_build.developer_id
     *
     * @mbg.generated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.project_name
     *
     * @return the value of devops_java_build.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.git_project_id
     *
     * @return the value of devops_java_build.git_project_id
     *
     * @mbg.generated
     */
    public Integer getGitProjectId() {
        return gitProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.git_branch
     *
     * @return the value of devops_java_build.git_branch
     *
     * @mbg.generated
     */
    public String getGitBranch() {
        return gitBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.code_path
     *
     * @return the value of devops_java_build.code_path
     *
     * @mbg.generated
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.build_path
     *
     * @return the value of devops_java_build.build_path
     *
     * @mbg.generated
     */
    public String getBuildPath() {
        return buildPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.version
     *
     * @return the value of devops_java_build.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.build_type
     *
     * @return the value of devops_java_build.build_type
     *
     * @mbg.generated
     */
    public String getBuildType() {
        return buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.jvm_options
     *
     * @return the value of devops_java_build.jvm_options
     *
     * @mbg.generated
     */
    public String getJvmOptions() {
        return jvmOptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.last_modify_time
     *
     * @return the value of devops_java_build.last_modify_time
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_java_build.create_time
     *
     * @return the value of devops_java_build.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public BuildCode toBuildCode() {
        BuildCode buildCode = new BuildCode();

        buildCode.setCodePath(this.codePath);
        buildCode.setBuildPath(this.buildPath);
        buildCode.setGitBranch(this.gitBranch);
        buildCode.setProjectName(this.projectName);
        return buildCode;
    }
}