package com.cenostack.ms.devops.dao;

import com.cenostack.ms.devops.entity.DevopsOpLogEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface DevopsOpLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    @Delete({
        "delete from devops_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    @Insert({
        "insert into devops_log (developer_id, ",
        "username, command, ",
        "args, dtime, content, ",
        "ddesc, result)",
        "values (#{developerId,jdbcType=INTEGER}, ",
        "#{username,jdbcType=VARCHAR}, #{command,jdbcType=VARCHAR}, ",
        "#{args,jdbcType=VARCHAR}, #{dtime,jdbcType=VARCHAR},",
        "#{content,jdbcType=VARCHAR},#{result,jdbcType=VARCHAR},",
        "#{ddesc,jdbcType=VARCHAR})"
    })
    int insert(DevopsOpLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    int insertSelective(DevopsOpLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, developer_id, username, command, args, dtime, content, ddesc, result, last_modify_time, ",
        "create_time",
        "from devops_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    DevopsOpLogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsOpLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_log
     *
     * @mbg.generated
     */
    @Update({
        "update devops_log",
        "set developer_id = #{developerId,jdbcType=INTEGER},",
          "username = #{username,jdbcType=VARCHAR},",
          "command = #{command,jdbcType=VARCHAR},",
          "args = #{args,jdbcType=VARCHAR},",
          "dtime = #{dtime,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "ddesc = #{ddesc,jdbcType=VARCHAR},",
          "result = #{result,jdbcType=VARCHAR},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DevopsOpLogEntity record);

    @Select({
            "select",
            "id, developer_id, username, command, args, dtime, content, ddesc, result, last_modify_time, ",
            "create_time",
            "from devops_log",
            "limit #{page,jdbcType=INTEGER},#{num,jdbcType=INTEGER}"
    })
    @ResultMap("com.jd.dkh.ms.devops.dao.DevopsOpLogEntityMapper.BaseResultMap")
    List<DevopsOpLogEntity> selectBaseByPage(Integer page,Integer num);
}