package com.cenostack.ms.devops.dao;

import com.cenostack.ms.devops.entity.JavaBuildEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface JavaBuildEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    @Delete({
        "delete from devops_java_build",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    @Insert({
        "insert into devops_java_build (developer_id, ",
        "project_name, git_project_id, ",
        "git_branch, code_path, ",
        "build_path, version, ",
        "build_type, jvm_options, ",
        "last_modify_time, create_time)",
        "values (#{developerId,jdbcType=INTEGER}, ",
        "#{projectName,jdbcType=VARCHAR}, #{gitProjectId,jdbcType=INTEGER}, ",
        "#{gitBranch,jdbcType=VARCHAR}, #{codePath,jdbcType=VARCHAR}, ",
        "#{buildPath,jdbcType=VARCHAR}, #{version,jdbcType=VARCHAR}, ",
        "#{buildType,jdbcType=VARCHAR}, #{jvmOptions,jdbcType=VARCHAR}, ",
        "#{lastModifyTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(JavaBuildEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    int insertSelective(JavaBuildEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, developer_id, project_name, git_project_id, git_branch, code_path, build_path, ",
        "version, build_type, jvm_options, last_modify_time, create_time",
        "from devops_java_build",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.jd.dkh.ms.devops.dao.JavaBuildEntityMapper.BaseResultMap")
    JavaBuildEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JavaBuildEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devops_java_build
     *
     * @mbg.generated
     */
    @Update({
        "update devops_java_build",
        "set developer_id = #{developerId,jdbcType=INTEGER},",
          "project_name = #{projectName,jdbcType=VARCHAR},",
          "git_project_id = #{gitProjectId,jdbcType=INTEGER},",
          "git_branch = #{gitBranch,jdbcType=VARCHAR},",
          "code_path = #{codePath,jdbcType=VARCHAR},",
          "build_path = #{buildPath,jdbcType=VARCHAR},",
          "version = #{version,jdbcType=VARCHAR},",
          "build_type = #{buildType,jdbcType=VARCHAR},",
          "jvm_options = #{jvmOptions,jdbcType=VARCHAR},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JavaBuildEntity record);

    @Select({
            "select",
            "id, developer_id, project_name, git_project_id, git_branch, code_path, build_path, ",
            "version, build_type, jvm_options, last_modify_time, create_time",
            "from devops_java_build",
            "where project_name = #{projectName,jdbcType=VARCHAR}"
    })
    @ResultMap("com.jd.dkh.ms.devops.dao.JavaBuildEntityMapper.BaseResultMap")
    JavaBuildEntity selectByProjectName(String projectName);

    @Select({
            "select",
            "count(id)",
            "from devops_java_build"
    })
    int count();
}